from .objects import MujocoObject, MujocoXMLObject, MujocoGeneratedObject

from .xml_objects import (
    TestXMLObject,
    CoffeeMachineXMLObject,
    WoodenPieceObject,
    DoorObject,
    SpinningPoleObject,
    BottleObject,
    CanObject,
    LemonObject,
    MilkObject,
    BreadObject,
    CerealObject,
    SquareNutObject,
    RoundNutObject,
    MilkVisualObject,
    BreadVisualObject,
    CerealVisualObject,
    CanVisualObject,
    PlateWithHoleObject,
)

from .generated_objects import (
    CompositeBodyObject,
    HingeStackObject,
    CoffeeMachineObject,
    CompositeObject,
    CompositeBoxObject,
    BoundingObject,
    BoxPatternObject,
    BoundingPatternObject,
    CupObject,
    PotWithHandlesObject,
    BoxObject,
    CylinderObject,
    BallObject,
    CapsuleObject,
    AnimalObject,
    CarObject,
    TrainObject,
    BipedObject,
    DumbbellObject,
    HammerObject,
    GuitarObject,
)
